// inject-config.js
// Runs during Netlify build — reads environment variables
// and writes scripts/firebase-config.js so the site can use them.
// This file IS committed to git. The generated firebase-config.js is NOT.

const fs = require('fs');
const path = require('path');

// Read from Netlify environment variables
const config = {
  apiKey:            process.env.FIREBASE_API_KEY            || '',
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN        || '',
  projectId:         process.env.FIREBASE_PROJECT_ID         || '',
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET     || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  appId:             process.env.FIREBASE_APP_ID             || ''
};

const certConfig = {
  issuer:    process.env.CERT_ISSUER    || 'PokerIQ Academy',
  course:    process.env.CERT_COURSE    || "Texas Hold'em Mastery",
  signature: process.env.CERT_SIGNATURE || 'PokerIQ',
  website:   process.env.CERT_WEBSITE   || 'pokeriq.netlify.app'
};

// Check all required vars are present
const missing = Object.entries(config)
  .filter(([, v]) => !v)
  .map(([k]) => k);

if (missing.length > 0) {
  console.warn('⚠️  Missing environment variables:', missing.join(', '));
  console.warn('   Site will load but Firebase features will be disabled.');
  console.warn('   Add them in: Netlify → Site config → Environment variables');
}

// Write the config file
const output = `// Auto-generated by inject-config.js during Netlify build
// Do not edit this file manually — set values in Netlify environment variables

window.FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)};

window.CERT_CONFIG = ${JSON.stringify(certConfig, null, 2)};
`;

const outputPath = path.join(__dirname, 'scripts', 'firebase-config.js');
fs.writeFileSync(outputPath, output);

console.log('✅ firebase-config.js generated successfully');
console.log('   Project ID:', config.projectId || '(not set)');
console.log('   Cert issuer:', certConfig.issuer);
